#!/usr/bin/env node
/**
 * gen-scopes — the scopes each app DECLARES, generated from its capability doc into
 * @jkos/suite-manifest, so jkAuth can derive what it may GRANT.
 *
 * WHY A GENERATED FILE. jkAuth mints every token's `scope` claim and never read an
 * app's capability doc: `capabilities_path` sat in its registry unfetched, and its
 * image carries none of the peers' source. So it granted a blanket ladder
 * (`<app>:read|write|create|update|delete|admin`) for EVERY registry app — including
 * apps that declare no writes and no admin surface at all. Jag chose (D1, 2026-09-16)
 * a build-time manifest over COPYing four apps' discovery.js into jkAuth's image or
 * fetching them at boot, accepting the stated cost: a NEW scope is a deploy-shaped
 * event, because jkAuth must be rebuilt to grant it. The exact precedent is
 * `apps/jkauth/public/jkos-tokens.css`, a checked-in mirror held by `check:tokens`.
 *
 * WHAT IT CHECKS, beyond "the file is fresh":
 *   · every app with `capabilities: true` in APPS has a capability doc module here — a
 *     new app cannot publish capabilities that silently never reach the grant;
 *   · every WRITE capability (non-GET) declares at least one scope — a write door with
 *     no declared scope is one no grant can be derived for (three BeigeBoard doors were
 *     exactly this until the day this landed);
 *   · every declared scope names its OWN app and a known verb.
 *
 * The module list is the prober's BACKEND_DOCS: one table of "where each app's
 * capability doc lives", not a second copy of it.
 *
 * Run:  node packages/suite-manifest/scripts/gen-scopes.mjs           # write
 *       node packages/suite-manifest/scripts/gen-scopes.mjs --check   # gate: fail if stale
 *       (wired as `pnpm check:scopes`, folded into `pnpm test:contracts`)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..');
const OUT = resolve(HERE, '../scopes.generated.js');
const require = createRequire(import.meta.url);
const CHECK = process.argv.includes('--check');

const { APPS } = require('../apps.js');
const { BACKEND_DOCS } = await import(pathToFileURL(resolve(ROOT, 'packages/suite-prober/src/sources.mjs')).href);

const VERBS = new Set(['read', 'write', 'create', 'update', 'delete', 'admin']);
const problems = [];
const declared = {};

for (const b of BACKEND_DOCS) {
  const mod = require(resolve(ROOT, b.module));
  const doc = mod.CAPABILITIES || mod.CAPABILITIES_DOC;
  if (!doc || !Array.isArray(doc.capabilities)) { problems.push(`${b.app}: ${b.module} exports no capability doc`); continue; }
  if (doc.app !== b.app) problems.push(`${b.module} declares app '${doc.app}', expected '${b.app}'`);
  const set = new Set();
  for (const c of doc.capabilities) {
    const scopes = [...(c.scope ? [c.scope] : []), ...(c.scopes || [])];
    if ((c.method || 'GET') !== 'GET' && scopes.length === 0) {
      problems.push(`${b.app}.${c.id} (${c.method} ${c.path}) is a write capability and declares no scope`);
    }
    for (const s of scopes) {
      const [app, verb, extra] = String(s).split(':');
      if (extra !== undefined || app !== b.app || !VERBS.has(verb)) {
        problems.push(`${b.app}.${c.id} declares '${s}' — a scope must be '${b.app}:<${[...VERBS].join('|')}>'`);
        continue;
      }
      set.add(s);
    }
  }
  declared[b.app] = [...set].sort();
}

const documented = new Set(BACKEND_DOCS.map((b) => b.app));
for (const a of APPS) {
  if (a.capabilities && !documented.has(a.id)) {
    problems.push(`APPS row '${a.id}' publishes capabilities but has no BACKEND_DOCS module — its scopes would never reach jkAuth`);
  }
}

const body = Object.keys(declared).sort()
  .map((app) => `  ${app}: Object.freeze(${JSON.stringify(declared[app])}),`).join('\n');
const text = `'use strict'
// GENERATED by packages/suite-manifest/scripts/gen-scopes.mjs — DO NOT EDIT.
// The scopes each app's capability doc DECLARES. jkAuth derives what it may grant from
// this (see grantableScopes in scopes.js). Regenerate after changing any capability's
// \`scope\`/\`scopes\`; \`pnpm check:scopes\` fails while it is stale.
module.exports = Object.freeze({
${body}
})
`;

if (problems.length) {
  for (const p of problems) console.error(`✗ ${p}`);
  console.error(`\n✗ check:scopes: ${problems.length} declaration problem(s)`);
  process.exit(1);
}

const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null;
if (CHECK) {
  if (current !== text) {
    console.error('✗ packages/suite-manifest/scopes.generated.js is STALE against the capability docs.\n'
      + '    Rerun:  node packages/suite-manifest/scripts/gen-scopes.mjs');
    process.exit(1);
  }
  for (const [app, s] of Object.entries(declared)) console.log(`✓ ${app}: ${s.join(', ')}`);
  console.log(`\n✓ check:scopes: every write capability declares a scope, and jkAuth's copy is fresh (${Object.keys(declared).length} apps)`);
} else {
  writeFileSync(OUT, text);
  console.log(`✓ wrote ${OUT}`);
}
