"""Shared fixtures: a synthetic FLAC, generated by the ffmpeg already required.

The point of generating audio rather than committing a fixture file is that the
whole suite then runs on a machine with no access to `/mnt/Luna` — which is most
machines, including CI and anyone reading this project as a portfolio piece. The
library-backed test is an ADDITIONAL check that skips cleanly when the mount is
absent, never the only one.

Every generated file gets a deliberately hostile name (Trap 20): an ampersand,
an apostrophe, brackets, and spaces, mirroring the real library's `again&again`
and `Today's Lesson.flac`. If any code path in this project ever grows a
`shell=True`, these tests fail rather than the backfill mangling a filename at
2 a.m.
"""
import os
import subprocess

# The three characters that break a shell, in one name, on purpose.
HOSTILE_NAME = "again&again - Today's Lesson [16B-44.1kHz]"


def have(binary):
    """Whether a binary is on PATH — for skipIf guards."""
    from shutil import which
    return which(os.environ.get(f'{binary.upper()}_BIN', binary)) is not None


def make_sine_flac(directory, seconds=3.0, freq=440.0, rate=44100, name=HOSTILE_NAME):
    """Write a mono sine FLAC and return its path.

    Generated at 44.1 kHz rather than the analysis rate so that `decode` has to
    actually resample — a decode test against a file already at 22.05 kHz would
    pass even if the `-ar` flag were dropped.
    """
    path = os.path.join(directory, f'{name}.flac')
    subprocess.run(
        [
            os.environ.get('FFMPEG_BIN', 'ffmpeg'), '-v', 'error', '-nostdin', '-y',
            '-f', 'lavfi',
            '-i', f'sine=frequency={freq}:duration={seconds}:sample_rate={rate}',
            '-ac', '1',
            path,
        ],
        stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        check=True, timeout=60,
    )
    return path


def first_library_track(limit_dirs=3):
    """One real FLAC from the library, or None if the mount is not there.

    Bounded: it stops at the first file it finds rather than walking 15,000 over
    a network share to answer "is there at least one".
    """
    from config import AUDIO_EXTS, LIBRARY_ROOT
    if not os.path.isdir(LIBRARY_ROOT):
        return None
    seen = 0
    for dirpath, dirnames, filenames in os.walk(LIBRARY_ROOT):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith('.'))
        for name in sorted(filenames):
            if name.lower().endswith(AUDIO_EXTS):
                return os.path.join(dirpath, name)
        seen += 1
        if seen > limit_dirs * 20:
            return None
    return None
