services:
  recipe-plugin:
    build:
      context: ../../
      dockerfile: docker/recipe/Dockerfile.plugin
    container_name: ordeck-recipe-plugin
    restart: unless-stopped
    ports:
      - "3004:80"
    networks:
      - ordeck-net

  recipe-api:
    build:
      context: ../../services/recipe-api
    container_name: ordeck-recipe-api
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ordeck-net

networks:
  ordeck-net:
    external: true
