#!/usr/bin/env node
// gen-native.mjs — project native/shells.js into the files the native builds read.
//
//   node native/gen-native.mjs           # write
//   node native/gen-native.mjs --check   # CI: assert every generated file is in sync (check:native)
//
// WHY THE OUTPUT IS CHECKED IN rather than produced inside Gradle: an origin list is a grant
// (see shells.js), and a grant should be reviewable in a diff in the exact form the APK will
// carry it — not reconstructed by a build step a reviewer has to run. It also keeps node off
// the Android build: Gradle and the Docker image never need it to read these.
//
// Written:
//   native/android/shells.json                          flavors + package ids + version, for Gradle
//   native/android/twa/src/<shell><Env>/res/values/shell.xml   per TWA × debug/release
//   native/android/twa/src/<shell><Env>/res/xml/shortcuts.xml
//   native/android/home/src/<env>/res/values/shell.xml         the home launcher × debug/release
//   native/desktop/src/shells.json                      what the Electron shell reads
//
// A shell's ICON and BAR COLOUR are not declared in shells.js: they are its start app's own
// web manifest (`apps/<start>/public/manifest.webmanifest` — the 512 px PNGs by purpose, and
// theme_color), so the installed app and the installed PWA cannot show two different faces.
//
// --check also fails on a generated variant directory no shell produces any more, so a
// removed shell cannot leave its old trust list behind in a source set Gradle still builds.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const require = createRequire(import.meta.url)
const {
  VERSION, STAGING_SUFFIX, shellConfig, versionCode, androidShells, desktopShells,
} = require('./shells.js')

const ENVS = ['debug', 'release']
const cap = (s) => s[0].toUpperCase() + s.slice(1)
const BANNER = 'GENERATED by native/gen-native.mjs from native/shells.js — do not hand-edit.'

/** Escape text for an Android string resource: XML-escape, then aapt's own specials
 *  (an unescaped " is silently DROPPED by aapt, which would corrupt the JSON below). */
function androidString(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/'/g, "\\'")
    .replace(/^([@?])/, '\\$1')
}
/** '\n' + each line + '\n', or a bare '\n' for none — so an empty list leaves no blank line. */
const lines = (arr) => '\n' + arr.map((l) => l + '\n').join('')
const xmlAttr = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

/** The Digital Asset Links statement an app carries to claim its origins — the app half of
 *  the handshake whose web half is infra/nginx/assetlinks.json. */
function assetStatements(origins) {
  return JSON.stringify(origins.map((site) => ({
    relation: ['delegate_permission/common.handle_all_urls'],
    target: { namespace: 'web', site },
  })))
}

function twaValues(cfg, face) {
  const extra = cfg.origins.filter((o) => o !== new URL(cfg.startUrl).origin)
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${BANNER} -->
<resources>
    <string name="app_name">${androidString(cfg.name)}</string>
    <string name="start_url">${androidString(cfg.startUrl)}</string>
    <string name="host">${androidString(cfg.host)}</string>
    <color name="shell_bar">${face.themeColor}</color>
    <!-- The app half of Digital Asset Links: the origins this APK claims. The web half is
         infra/nginx/assetlinks.json, served by every one of these origins. -->
    <string name="asset_statements">${androidString(assetStatements(cfg.origins))}</string>
    <!-- Origins the TWA keeps full-screen besides the start origin. Anything else opens in
         the browser. -->
    <string-array name="additional_trusted_origins">${lines(extra.map((o) => `        <item>${androidString(o)}</item>`))}    </string-array>${lines(cfg.shortcuts.map((s) => `    <string name="shortcut_${s.id}">${androidString(s.name)}</string>`))}</resources>
`
}

function twaShortcuts(cfg) {
  const items = cfg.shortcuts.map((s) => `    <shortcut
        android:shortcutId="${xmlAttr(s.id)}"
        android:enabled="true"
        android:icon="@mipmap/ic_launcher"
        android:shortcutShortLabel="@string/shortcut_${s.id}">
        <intent
            android:action="android.intent.action.VIEW"
            android:targetPackage="${xmlAttr(cfg.applicationId)}"
            android:targetClass="com.google.androidbrowserhelper.trusted.LauncherActivity"
            android:data="${xmlAttr(s.url)}" />
    </shortcut>`)
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${BANNER} -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
${items.join('\n')}${items.length ? '\n' : ''}</shortcuts>
`
}

function homeValues(cfg, face) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${BANNER} -->
<resources>
    <string name="app_name">${androidString(cfg.name)}</string>
    <string name="start_url">${androidString(cfg.startUrl)}</string>
    <color name="shell_bar">${face.themeColor}</color>
    <!-- The ONLY origin the native bridge answers. Never jkAuth, never a peer app. -->
    <string name="bridge_origin">${androidString(cfg.bridgeOrigin)}</string>
    <!-- Navigation stays inside the launcher only on these origins; anything else is refused
         (a kiosk does not hand a guest the browser). -->
    <string-array name="shell_origins">${lines(cfg.origins.map((o) => `        <item>${androidString(o)}</item>`))}    </string-array>
</resources>
`
}

/** Icon paths (repo-relative) and theme colour from an app's web manifest. */
function webManifest(appId) {
  const rel = `apps/${appId}/public/manifest.webmanifest`
  const m = JSON.parse(readFileSync(join(ROOT, rel), 'utf8'))
  const icon = (purpose) => {
    const i = (m.icons || []).find((x) => x.type === 'image/png' && x.sizes === '512x512'
      && (x.purpose || 'any').split(/\s+/).includes(purpose))
    if (!i) throw new Error(`gen-native: ${rel} has no 512x512 PNG icon with purpose '${purpose}'`)
    const path = `apps/${appId}/public/${i.src.replace(/^\.?\//, '')}`
    if (!existsSync(join(ROOT, path))) throw new Error(`gen-native: ${rel} names ${path}, which does not exist`)
    return path
  }
  if (!/^#[0-9a-f]{6}$/i.test(m.theme_color || '')) throw new Error(`gen-native: ${rel} theme_color is not #rrggbb`)
  return { themeColor: m.theme_color.toLowerCase(), maskable: icon('maskable'), any: icon('any') }
}

/* ── the file set ───────────────────────────────────────────────────────────── */

const files = new Map()   // repo-relative path → content
const expectVariantDirs = { 'native/android/twa/src': new Set(), 'native/android/home/src': new Set() }

const twa = androidShells().filter((s) => s.android === 'twa')
const homes = androidShells().filter((s) => s.android === 'home')
if (homes.length !== 1) throw new Error(`gen-native: exactly one home shell expected, found ${homes.length}`)
const home = homes[0]

files.set('native/android/shells.json', JSON.stringify({
  _comment: BANNER,
  version: VERSION,
  versionCode: versionCode(),
  stagingSuffix: STAGING_SUFFIX,
  twa: twa.map((s) => ({ id: s.id, package: s.package, icon: webManifest(s.start).maskable })),
  home: { id: home.id, package: home.package, icon: webManifest(home.start).maskable },
}, null, 2) + '\n')

for (const s of twa) {
  for (const env of ENVS) {
    const cfg = shellConfig(s, env)
    const dir = `native/android/twa/src/${s.id}${cap(env)}`
    expectVariantDirs['native/android/twa/src'].add(`${s.id}${cap(env)}`)
    files.set(`${dir}/res/values/shell.xml`, twaValues(cfg, webManifest(s.start)))
    files.set(`${dir}/res/xml/shortcuts.xml`, twaShortcuts(cfg))
  }
}
for (const env of ENVS) {
  expectVariantDirs['native/android/home/src'].add(env)
  files.set(`native/android/home/src/${env}/res/values/shell.xml`, homeValues(shellConfig(home, env), webManifest(home.start)))
}

const desktop = {}
for (const s of desktopShells()) {
  const face = webManifest(s.start)
  desktop[s.id] = {
    package: s.package, icon: face.any, themeColor: face.themeColor,
    debug: shellConfig(s, 'debug'), release: shellConfig(s, 'release'),
  }
}
files.set('native/desktop/src/shells.json', JSON.stringify({
  _comment: BANNER, version: VERSION, shells: desktop,
}, null, 2) + '\n')

/* ── write / check ──────────────────────────────────────────────────────────── */

if (process.argv.includes('--check')) {
  let drift = 0
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel)
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null
    if (current !== content) {
      console.error(`✗ ${rel} is ${current === null ? 'missing' : 'out of sync'} — run: node native/gen-native.mjs`)
      drift++
    }
  }
  // Variant source sets are ours alone: main/ and test/ are hand-written, every other
  // directory must be one a shell generates.
  for (const [base, want] of Object.entries(expectVariantDirs)) {
    const abs = join(ROOT, base)
    const have = existsSync(abs) ? readdirSync(abs, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name) : []
    for (const d of have) {
      if (d === 'main' || d === 'test' || want.has(d)) continue
      console.error(`✗ ${base}/${d} is a variant no shell generates — a stale trust list Gradle would still build; delete it`)
      drift++
    }
  }
  if (drift) process.exit(1)
  console.log(`✓ native: ${files.size} generated files in sync with native/shells.js`)
} else {
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel)
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, content)
    console.log(`✓ wrote ${relative(ROOT, abs)}`)
  }
}
