services:
  plex-plugin:
    build:
      context: ../../
      dockerfile: docker/plex/Dockerfile.plugin
    container_name: ordeck-plex-plugin
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - ordeck-net

  plex-api:
    build:
      context: ../../services/plex-api
    container_name: ordeck-plex-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ordeck-net

networks:
  ordeck-net:
    external: true
